# Generated by Django 4.0.3 on 2022-06-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
